site_name: YOLO Object Sorting Documentation
site_url: https://sidhgurnani.github.io/yolo-object-sorter-docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - search.suggest
    - search.highlight
    - toc.integrate
    - navigation.footer
    # - content.action.edit
    # - content.action.view
    - content.code.copy
  palette:
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Fira Code
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sidh-gurnani/
      name: Connect on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/sidhgurnani
    - icon: fontawesome/solid/envelope
      link: mailto:sidh.gurnani@gmail.com

nav:
  - Home: index.md
  - Milestones: milestones.md
  - Introduction and Motivation: intro.md
  - Architecture: architecture.md
  - Development: 
      - Software Versions: software_development.md
      - Prototype Versions: prototype_development.md
  - Final Testing: final_testing.md
  - Results and Reflections: results.md

repo_url: https://github.com/sidhgurnani/yolo-object-sorter-docs
repo_name: GitHub
edit_uri: edit/main/docs/